import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';

test('built stdio plugin accepts verified conversation links and exposes them in live board results', async t => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'myissue-conversation-mcp-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const client = new Client({ name: 'conversation-acceptance', version: '1' });
  const transport = new StdioClientTransport({ command: process.execPath, args: [path.resolve('plugins/myissue/scripts/server.cjs')], env: { ...Object.fromEntries(Object.entries(process.env).filter((entry): entry is [string, string] => typeof entry[1] === 'string')), MYISSUE_CONFIG_DIR: path.join(root, '.config'), MYISSUE_CODEX_BIN: path.join(root, 'missing-codex') } });
  await client.connect(transport); t.after(() => client.close());
  const catalog = await client.listTools();
  assert.equal(catalog.tools.find(tool => tool.name === 'link_conversation')?.annotations?.readOnlyHint, false);
  const invoke = async (name: string, args: Record<string, unknown>) => {
    const response = await client.callTool({ name, arguments: args });
    assert.ok(!response.isError, JSON.stringify(response.structuredContent));
    return response.structuredContent as any;
  };
  const { issue } = await invoke('create_issue', { root, name: '实际工具关联', properties: { status: 'todo' } });
  const url = 'codex://threads/verified-thread';
  const linked = await invoke('link_conversation', { root, id: issue.id, revision: issue.revision, url, title: '已确认的对话' });
  assert.deepEqual(linked.issue.properties.current_conversation, { url, title: '已确认的对话' });
  assert.deepEqual((await invoke('list_issues', { root })).board.issues[0].properties.current_conversation, linked.issue.properties.current_conversation);
  const stale = await client.callTool({ name: 'link_conversation', arguments: { root, id: issue.id, revision: issue.revision, url } });
  assert.equal(stale.isError, true);
  assert.equal((stale.structuredContent as any).error.code, 'CONFLICT');
  const source = { url: 'codex://threads/comment-origin', title: '评论来源' };
  const commented = await invoke('append_comment', { root, id: issue.id, revision: linked.issue.revision, body: '真实评论', author: 'Codex', actor: 'gpt-6.1-sol', conversation: source });
  const comment = commented.issue.comments[0];
  assert.deepEqual(commented.issue.properties.comment_conversations[comment.id], source);
  assert.deepEqual(commented.issue.properties.current_conversation, linked.issue.properties.current_conversation);
  assert.match(comment.heading, /gpt-6\.1-sol$/);
  assert.equal(catalog.tools.find(tool => tool.name === 'link_comment_conversation')?.annotations?.readOnlyHint, false);
  const changedSource = await invoke('link_comment_conversation', { root, id: issue.id, revision: commented.issue.revision, commentId: comment.id, url: 'codex://threads/verified-correction', title: '来源更正' });
  assert.deepEqual(changedSource.issue.comments, commented.issue.comments);
  const invalidModel = await client.callTool({ name: 'append_comment', arguments: { root, id: issue.id, revision: changedSource.issue.revision, body: '不得写入', author: 'Codex', actor: 'gpt-6' } });
  assert.equal(invalidModel.isError, true);
  assert.equal((invalidModel.structuredContent as any).error.code, 'INVALID_MODEL');
  assert.equal((await invoke('get_issue', { root, id: issue.id })).issue.comments.length, 1);
});
