import test from 'node:test';
import assert from 'node:assert/strict';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { mkdtemp, mkdir, rm, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { UI_URI } from '../src/server.js';

test('built plugin exposes independent UI, real CRUD and dispatch context over MCP', async t => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'myissue-mcp-')); t.after(() => rm(root, { recursive: true, force: true }));
  const client = new Client({ name: 'myissue-acceptance', version: '1' });
  const preferencesDir = path.join(root, '.plugin-preferences');
  const transport = new StdioClientTransport({ command: process.execPath, args: [path.resolve('plugins/myissue/scripts/server.cjs'), '--root', root], env: { ...Object.fromEntries(Object.entries(process.env).filter((entry): entry is [string, string] => typeof entry[1] === 'string')), MYISSUE_CONFIG_DIR: preferencesDir, PLUGIN_DATA: path.join(root, 'legacy-data'), MYISSUE_CODEX_BIN: path.join(root, 'unavailable-desktop-cli') } });
  await client.connect(transport); t.after(() => client.close());
  const catalog = await client.listTools(); const open = catalog.tools.find(tool => tool.name === 'open_board')!;
  assert.deepEqual((open._meta?.['openai/ui'] as any).entrypoints, [{ type: 'global' }, { type: 'thread' }]);
  const resource = await client.readResource({ uri: UI_URI }); assert.ok('text' in resource.contents[0]); assert.match(resource.contents[0].text, /myIssue/); assert.equal(resource.contents[0].mimeType, 'text/html;profile=mcp-app');
  // Cached entrypoints from a previous release must still resolve in a new server.
  assert.equal((open._meta?.ui as any).resourceUri, UI_URI);
  assert.equal(open._meta?.['openai/outputTemplate'], UI_URI);
  const legacy = await client.readResource({ uri: 'ui://myissue/board-v1.html' });
  assert.equal(legacy.contents[0].uri, 'ui://myissue/board-v1.html');
  assert.deepEqual({ ...legacy.contents[0], uri: UI_URI }, resource.contents[0]);
  const invoke = async (name: string, args: any = {}) => (await client.callTool({ name, arguments: args })).structuredContent as any;
  const created = (await invoke('create_issue', { root, name: '从对话创建', properties: { status: 'todo', future: 'preserved' }, description: '真实上下文' })).issue;
  const read = (await invoke('get_issue', { root, id: created.id })).issue; assert.equal(read.revision, created.revision);
  const updated = (await invoke('update_issue', { root, id: created.id, revision: read.revision, properties: { status: 'in_progress' } })).issue;
  const commented = (await invoke('append_comment', { root, id: created.id, revision: updated.revision, body: '真实评论', author: 'acceptance', actor: 'human' })).issue;
  const dispatch = await invoke('prepare_dispatch', { root, id: created.id });
  assert.match(dispatch.prompt, /真实评论/); assert.match(dispatch.prompt, /从对话创建/);
  const board = await invoke('open_board', { root, issueId: created.id }); assert.equal(board.board.issues[0].comments.length, 1);
  assert.equal(board.username, os.userInfo().username);
  assert.equal((await invoke('list_projects', { refresh: false })).username, board.username);
  assert.deepEqual(JSON.parse(await readFile(path.join(preferencesDir, 'projects.json'), 'utf8')), { version: 1, projects: [{ root, name: path.basename(root) }], lastRoot: root });
  const mention = await invoke('search_mentions', { query: '从对话' });
  assert.equal(mention.items.length, 1);
  const mentionResource = await client.readResource({ uri: mention.items[0].resourceUri });
  assert.ok('text' in mentionResource.contents[0]); assert.equal(mentionResource.contents[0].text, commented.raw);
  assert.equal(await readFile(path.join(root, 'issues', created.filename), 'utf8'), commented.raw);
  const stale = await client.callTool({ name: 'update_issue', arguments: { root, id: created.id, revision: created.revision, name: 'Overwrite' } });
  assert.equal(stale.isError, true); assert.equal((stale.structuredContent as any).error.code, 'CONFLICT');
  assert.equal(catalog.tools.find(tool => tool.name === 'upload_attachment')?.annotations?.readOnlyHint, false);
  assert.equal(catalog.tools.find(tool => tool.name === 'read_attachment')?.annotations?.readOnlyHint, true);
  const attached = await invoke('upload_attachment', { root, id: created.id, revision: commented.revision, name: 'context.txt', data: Buffer.from('portable attachment').toString('base64') });
  assert.match(attached.issue.description, /context.txt/);
  assert.deepEqual(attached.issue.comments, commented.comments);
  const attachment = await invoke('read_attachment', { root, id: created.id, path: attached.attachment.path });
  assert.equal(Buffer.from(attachment.attachment.data, 'base64').toString(), 'portable attachment');
  assert.match((await invoke('prepare_dispatch', { root, id: created.id })).prompt, /attachments\//);
});
